### ISSUE TITLE
ReleaseAPI doesn't work

### ISSUE THREAD

**Issue by mswilson4040** [Microsoft/vsts-node-api#133] opened 2018-01-12 00:07 UTC
I am trying to use the release API to get get the approvals for a given release. However, any method I try to use always returns:

```
(node:5484) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to find api location for area: Release id: cd1502bb-3c73-4e11-80a6-d11308dceae5
(node:5484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is my code:

```
        const vsts = require('vso-node-api');

        const pat = '<pat>';
        const authHandler = vsts.getPersonalAccessTokenHandler(pat);
        const serverUrl = 'https://company.visualstudio.com/DefaultCollection';
        const connection = new vsts.WebApi(serverUrl, authHandler);
        const releaseApi = connection.getReleaseApi(serverUrl);
        releaseApi.getMetrics('headset').then( test => {
            if (test) {

            }
        });
```

I saw some threads about removing the 'DefaultCollection' from the url and it doesn't change anything. I am using the buildsApi with no problem, so since I am unable to get any method to work within the release api, it leads me to believe it doesn't work.

**Comment by bryanmacfarlane** [comment] 2018-01-17 22:22
Same root cause as this issue: https://github.com/Microsoft/vsts-node-api/issues/131 

See comment

**Comment by bryanmacfarlane** [comment] 2018-01-17 22:25
dupe of https://github.com/Microsoft/vsts-node-api/issues/118

**Closed by bryanmacfarlane** 2018-01-17 22:25 UTC
